### PR TITLE
Give option for additional output JSON/Extended JSON

### PR DESCRIPTION
**Pull request by McStork**
* Add a new option 'add_output' in the config file. Possible values are json and ext_json
* add_output can only be set once in the config file
* 'add_output json' dates comply to iso8601
* 'add_output ext_json' dates comply to the format specified for Extended JSON (MongoDB related)

### CODE REVIEW

**Comment by jelu** [comment]
Please update/rebase against upstream/develop to get the Travis config.

**Comment by McStork** [comment]
Rebased

**Comment by jelu** [comment]
I will give this a thorough look tomorrow, there are a few things that will need to be discussed before any merge can happen.

**Comment by jelu** [comment]
I think it's good to get JSON output format but:
- I do not like it being "additional output", I think you should have a choice between output format (or many of them)
- I do not like "Extended JSON" because there isn't anything extended about it and its purely for MongoDB, what would be better here is really a MongoDB connector.
- You shouldn't really `printf()` any format, better to use a library. I know that the XML is manually created but that can be changed.

Can you explain the difference between "JSON" and "Extended JSON" ?

Seeing that the PR needs a lot of changes I am all for doing the changes in a new branch/PR and credit you for the work unless you want to make the changes in this PR yourself?

**Comment by McStork** [comment]
I also like the idea you suggest of having a choice between output formats. I implemented it as an "additional output" option but it really was just not to break anybody config file.

The only different between JSON and Extended JSON in this PR is about date fields. In JSON, they are ISO8601 whereas in Extended JSON the date has to be a value in a "$date" field.([MongoDB doc](https://docs.mongodb.org/manual/reference/mongodb-extended-json/#date)).
This is a minor difference and someone wanting to import JSON files in MongoDB could implement a filter to modify the dates fields so it comply to the Extended JSON format. So IMO it's not a big deal if there is no native output of Extended JSON in DSC.

Concerning the changes you want to do (refactor code for writing in files, [remove Hapy](https://github.com/DNS-OARC/dsc/issues/9)):

> unless you want to make the changes in this PR yourself?

Are you suggesting to merge this PR and update the code yourself or that I reopen this PR on a new DSC feature branch?

**Comment by McStork** [comment]
However, I think that when people will come to choose a database for storing and processing DSC reports, MongoDB might be the most serious contender. So having native support for Extended JSON should be considered.

**Comment by jelu** [comment]
I will continue the JSON work based on your branch but for now I will close this PR as wontfix.

For the MongoDB support, can look at refactoring to provide interfaces to develop plugins for databases so that you can put the statistics directly into MongoDB.

**Pull request closed without merging**
