### PR TITLE
kdrenard label length indexer and count-only dataset option

### PR DESCRIPTION
**Pull request by kdrenard**
Adding indexer for label count (similar to qnamelen) and dataset option for only returning a count of cells versus all cell data.

Question for return value of parser (parse_conf.c:301).  Not sure if 1 or -1 is appropriate here.

### CODE REVIEW

**Comment by jelu** [comment]
Uhm, what is the point of `count-only`? Why would you want that?

**Comment by kdrenard** [comment]
> Uhm, what is the point of `count-only`? Why would you want that?

Our use case was pretty limited, but we wanted to see how "wide" our client base (client_subnet) was and look for trends.  Output size was getting unruly with all the subnets listed.  I have another way of doing this now and if you wanted to skip this feature, that is perfectly fine.  Thanks!

**Comment by kdrenard** [comment]
> Output size was getting unruly with all the subnets listed.

Yeah, you could just set max-cells down to a low value (0?) and use SKIPPED* to get your counts.  Please disregard the 'count-only' option.

**Comment by jelu** [comment]
>  Please disregard the 'count-only' option.

Sure, I'm gonna remove that code for now. If something like that is needed in the future I think it might be better to implement indexers that count uniqueness of elements.

Btw, I'm going to rename `labellen` to `label_count` - as it's actually counting labels and not their lengths.

**Comment by jelu** [comment]
#build

**Pull request merged**
